/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.node;

import java.util.*;
import net.sourceforge.texlipse.bibparser.analysis.*;

@SuppressWarnings("nls")
public final class ABibtex extends PBibtex
{
    private final LinkedList<PContent> _content_ = new LinkedList<PContent>();

    public ABibtex()
    {
        // Constructor
    }

    public ABibtex(
        @SuppressWarnings("hiding") List<PContent> _content_)
    {
        // Constructor
        setContent(_content_);

    }

    @Override
    public Object clone()
    {
        return new ABibtex(
            cloneList(this._content_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABibtex(this);
    }

    public LinkedList<PContent> getContent()
    {
        return this._content_;
    }

    public void setContent(List<PContent> list)
    {
        this._content_.clear();
        this._content_.addAll(list);
        for(PContent e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._content_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._content_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PContent> i = this._content_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PContent) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
