/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.node;

import net.sourceforge.texlipse.bibparser.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyValOrSid extends PValOrSid
{

    public AEmptyValOrSid()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyValOrSid();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyValOrSid(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
