/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.node;

import net.sourceforge.texlipse.bibparser.analysis.*;

@SuppressWarnings("nls")
public final class APreContent extends PContent
{
    private PPreambleEntry _preambleEntry_;

    public APreContent()
    {
        // Constructor
    }

    public APreContent(
        @SuppressWarnings("hiding") PPreambleEntry _preambleEntry_)
    {
        // Constructor
        setPreambleEntry(_preambleEntry_);

    }

    @Override
    public Object clone()
    {
        return new APreContent(
            cloneNode(this._preambleEntry_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPreContent(this);
    }

    public PPreambleEntry getPreambleEntry()
    {
        return this._preambleEntry_;
    }

    public void setPreambleEntry(PPreambleEntry node)
    {
        if(this._preambleEntry_ != null)
        {
            this._preambleEntry_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preambleEntry_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._preambleEntry_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._preambleEntry_ == child)
        {
            this._preambleEntry_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._preambleEntry_ == oldChild)
        {
            setPreambleEntry((PPreambleEntry) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
