/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sourceforge.texlipse.bibparser.node;

import net.sourceforge.texlipse.bibparser.analysis.*;

@SuppressWarnings("nls")
public final class AStrContent extends PContent
{
    private PStringEntry _stringEntry_;

    public AStrContent()
    {
        // Constructor
    }

    public AStrContent(
        @SuppressWarnings("hiding") PStringEntry _stringEntry_)
    {
        // Constructor
        setStringEntry(_stringEntry_);

    }

    @Override
    public Object clone()
    {
        return new AStrContent(
            cloneNode(this._stringEntry_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStrContent(this);
    }

    public PStringEntry getStringEntry()
    {
        return this._stringEntry_;
    }

    public void setStringEntry(PStringEntry node)
    {
        if(this._stringEntry_ != null)
        {
            this._stringEntry_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringEntry_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringEntry_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringEntry_ == child)
        {
            this._stringEntry_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringEntry_ == oldChild)
        {
            setStringEntry((PStringEntry) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
